### ISSUE TITLE
Feature: install additional flake8 plugins

### ISSUE THREAD

**Issue by jkrooskos** [adventurerscodex/uat#107]
### Proposed Feature

Add additional flake8 plugins to test additional code style

- [ ] pip install pep8-naming, flake8-import-order, flake8-bugbear, and flake8-docstrings
- [ ] update .flake8 to match config below (application-import-names should match the project modules)
- [ ] run flake8 and fix errors
- [ ] update the requirements file (pip freeze > requirements.txt)

**Comment by jkrooskos** [comment]
```
[flake8]
import-order-style=google
exclude=.git,__pycache__
ignore =
    N806,   # Variables can be CamelCase
max-line-length=100
```

**Comment by Seankipp** [comment]
I think in my excitement I forgot to update the requirements.txt file. Should I just create a new branch and do: `pip freeze requirements.txt`
