### ISSUE TITLE
Remove instances of '\t' in the tests

### ISSUE THREAD

**Issue by jkrooskos** [adventurerscodex/uat#16]
This was used to simulate a tab after entering data in an element. A better way to do this is the following:

from selenium.webdriver.common.keys import Keys

element.send_keys(Keys.TAB)

Below are the occurrences that should be replaced:

tests/core/dm_tools/test_overview.py:    dm_overview.setting = 'The Lost World\t'
tests/core/dm_tools/test_overview.py:    dm_overview.dm_name = 'Automated Testing Bot\t'
tests/core/player_tools/test_inventory.py:    coins_table.copper = '100\t'
tests/core/player_tools/test_inventory.py:    coins_table.copper = '49\t'
tests/core/player_tools/test_inventory.py:    coins_table.copper = '50\t'
tests/core/player_tools/test_profile.py:    profile.name = 'Gandalf\t'
tests/core/player_tools/test_profile.py:    profile.background = 'Sage\t'
tests/core/player_tools/test_profile.py:    profile.alignment = 'Chaotic Good\t'
tests/core/player_tools/test_profile.py:    profile.deity = 'Moridin\t'
tests/core/player_tools/test_profile.py:    profile.race = 'Gnome\t'
tests/core/player_tools/test_profile.py:    profile.class_ = 'Fighter\t'
tests/core/player_tools/test_profile.py:    profile.gender = 'Male\t'
tests/core/player_tools/test_profile.py:    profile.age = '12\t'
tests/core/player_tools/test_profile.py:    background.traits = 'Traits...\t'
tests/core/player_tools/test_profile.py:    background.ideals = 'Ideals...\t'
tests/core/player_tools/test_profile.py:    background.bonds = 'Bonds...\t'
tests/core/player_tools/test_profile.py:    background.flaws = 'Flaws...\t'
tests/core/player_tools/test_profile.py:    appearance.height = '5ft\t'
tests/core/player_tools/test_profile.py:    appearance.weight = '165\t'
tests/core/player_tools/test_profile.py:    appearance.hair_color = 'Brown\t'
tests/core/player_tools/test_profile.py:    appearance.eye_color = 'Brown\t'
tests/core/player_tools/test_profile.py:    appearance.skin_color = 'Fair\t'
tests/core/player_tools/test_equipment.py:    armor_add.stealth = 'Disadvantage\t'
tests/core/player_tools/test_equipment.py:    armor_edit.stealth = 'Advantage\t'

**Comment by Seankipp** [comment]
Complete; looks like you may have taken care of the instances of \t in the test_equipment.py file.

**Comment by jkrooskos** [comment]
closed via #18
