### ISSUE TITLE
Add Item Factory

### ISSUE THREAD

**Issue by jkrooskos** [adventurerscodex/uat#23]
name = models.CharField(max_length=40)
    description = models.TextField(blank=True, null=True)
    quantity = models.IntegerField(default=1)
    weight = models.IntegerField(default=0)
    cost = models.IntegerField(default=0)
    currency_denomination = models.CharField(max_length=10, blank=True, null=True)

**Comment by Seankipp** [comment]
In the other factories built the documentation you provided from the code references "price" (example from weapon factory, below), do we distinguish between that and "cost"?

`price = models.IntegerField(default=0)`
