### ISSUE TITLE
Create a spell factory

### ISSUE THREAD

**Issue by jkrooskos** [adventurerscodex/uat#32]
For reference:

class AbstractSpell(models.Model):
    name = models.CharField(max_length=40)
    type = models.CharField(max_length=40, default='')
    damage = models.CharField(max_length=40, default='')
    damage_type = models.CharField(max_length=40, default='')
    school = models.CharField(max_length=40, default='')
    level = models.IntegerField(default=0)
    description = models.TextField(blank=True, null=True)
    material_components = models.TextField(blank=True, null=True)
    is_ritual = models.BooleanField(default=False)
    prepared = models.BooleanField(default=False)
    always_prepared = models.BooleanField(default=False)
    casting_time = models.CharField(max_length=100, default='')
    components = models.TextField(default='')
    duration = models.TextField(default='')
    range = models.TextField(default='')
    duration = models.TextField(default='')

**Comment by Seankipp** [comment]
duration is listed twice for Spells? should I include twice?

`components = models.TextField(default='')
duration = models.TextField(default='')
range = models.TextField(default='')
duration = models.TextField(default='')`

**Comment by jkrooskos** [comment]
Nope just once. I'll let the API folks know. Thanks.
